In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
array_1d = np.array([1, 2, 3, 4, 5, 6])

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

array_1d

array([1, 2, 3, 4, 5, 6])

In [4]:
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
array_2d[0, 0] # array_2d[0][0]

1

In [7]:
array_2d[0][0] = 2

In [8]:
array_linspace = np.linspace(0, 10, 5)
array_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
print(array_2d.shape, array_2d.ndim, array_2d.size, sep='\n')

(2, 3)
2
6


In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random((2, 3))

array([[0.38861389, 0.60783471, 0.5368452 ],
       [0.25630063, 0.29712458, 0.17654579]])

In [14]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

array_a + array_b

array([5, 7, 9])

In [15]:
array_a * 2

array([2, 4, 6])

In [16]:
print("Максимум в массиве:", np.max(array_2d))
print("Минимум в массиве:", np.min(array_2d))
print("Среднее значение в массиве:", np.mean(array_2d))
print("Сумма всех элементов в массиве:", np.sum(array_2d))

Максимум в массиве: 6
Минимум в массиве: 2
Среднее значение в массиве: 3.6666666666666665
Сумма всех элементов в массиве: 22


In [17]:
array_2d > 5

array([[False, False, False],
       [False, False,  True]])

In [18]:
np.where(array_2d > 5, 100, -100)

array([[-100, -100, -100],
       [-100, -100,  100]])

In [19]:
array_1d.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
array_2d.flatten()

array([2, 2, 3, 4, 5, 6])

In [21]:
np.concatenate([array_a, array_b])

array([1, 2, 3, 4, 5, 6])

In [22]:
for element in array_2d.flat:
    display(element)

2

2

3

4

5

6

In [24]:
np.array(array_2d.flat)

array([2, 2, 3, 4, 5, 6])